STELLAR_BURGERS_MAIN_PAGE = "https://stellarburgers.nomoreparties.site/"
STELLAR_BURGERS_LOGIN_PAGE = f"{STELLAR_BURGERS_MAIN_PAGE}login"
STELLAR_BURGERS_FORGOT_PASSWORD_PAGE = f"{STELLAR_BURGERS_MAIN_PAGE}forgot-password"
STELLAR_BURGERS_FORGOT_REGISTER_PAGE = f"{STELLAR_BURGERS_MAIN_PAGE}register"
